
###

POST http://localhost:8080/api/profile
Content-Type: application/json

{
  "username": "test99999999999997777775",
  "firstName": "test99999999999997777775",
  "surname": "test99999999999997777775",
  "password": "test99999999999997777775"
}


###

POST http://localhost:8081/api/login
Content-Type: application/json

{
  "login": "test777771239",
  "password": "test777771293"
}

###

GET http://127.0.0.1:8080/api/profiles
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiZXhwIjoyMjIwMTc0MjQxfQ.Rypdn8LPMU7Ocp-JAHP8JEMAUUse76eKCZ3CrGTwIcuUolrATIqfLMq0-aLDZCkjUX-I2AdY_i798_2IKCVHQw


###

GET http://localhost:8080/api/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDA1OTc3ODEiLCJleHAiOjIyMTc0OTExMDN9.uRsNK9rx_EXdFoV-118pXomhXMGGMiVzrGy3BteiDMAR68WFbXL94Y-gJPsQuty4XOSlZC7psOUIdEOgAiMoTg

###

PUT http://localhost:8080/api/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw
Content-Type: application/json

{
  "firstName": "test2",
  "surname": "test4",
  "city": "default",
  "birthDate": "2012-01-02",
  "gender": "M",
  "interests": "test test"
}


###

GET http://localhost:8080/api/friend/1

###

GET http://localhost:8080/api/friend
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw


###

POST http://localhost:8080/api/friend
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw
Content-Type: application/json

{
  "friendId": 3
}

###

DELETE http://localhost:8080/api/friend/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiZXhwIjoyMjIwMTc0MjQxfQ.Rypdn8LPMU7Ocp-JAHP8JEMAUUse76eKCZ3CrGTwIcuUolrATIqfLMq0-aLDZCkjUX-I2AdY_i798_2IKCVHQw


### MESSAGING



GET http://localhost:8080/api/chat
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoyMjIwNTIyMDE2fQ.7XDyeOD_0MBC0HUQM5_Lh6XWCWwGy_-xE502dikNdYVYI2y3BbxGwB0hI_nKEMTfgjUl0T4ltWagFcf7UUoVyQ
Content-Type: application/json


### 1


POST http://localhost:8080/api/chat/message
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoyMjIwNTIyMDE2fQ.7XDyeOD_0MBC0HUQM5_Lh6XWCWwGy_-xE502dikNdYVYI2y3BbxGwB0hI_nKEMTfgjUl0T4ltWagFcf7UUoVyQ
Content-Type: application/json

{
  "participantId": 2,
  "message": "test message 555"
}

### 2

POST http://localhost:8080/api/chat/message
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiZXhwIjoyMjIwNTIyMjU4fQ.FKM2tBA-nnHAt6B5FPvzBpwcmAADKGQWzcajGDb7kLEP4XEHcguCbjmiA2CUNUj6dXT7NFUyIQF2kI87DQSwmA
Content-Type: application/json

{
  "participantId": 1,
  "message": "test message 777"
}