
###

POST http://localhost:8080/api/profile
Content-Type: application/json

{
  "username": "test99999999999997777775",
  "firstName": "test99999999999997777775",
  "surname": "test99999999999997777775",
  "password": "test99999999999997777775"
}


###

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "login": "test777771239",
  "password": "test777771293"
}

###

GET http://127.0.0.1:8080/api/profiles?firstName=test777771239
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjE0NDY0Njg1fQ.rSaaZp-j3311Onu1Ua6XKvFzHkTRh6OQ4dFZL7Yiw4oO0pfgbMlZd6Obl_MtWF62PFYNwgjhCCRX7TlzjXGbuw


###

GET http://localhost:8080/api/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDA1OTY4OTQiLCJleHAiOjE2MTM4NTMwMzV9.DHERq1ks7mxkjzxajsVOAaaXBs2tjmKTxJrVUbvfua1ZkzVcPmqmzqfbxt6MxeS3Oh6-mWYl5AXbbHwW5c6cNw

###

PUT http://localhost:8080/api/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw
Content-Type: application/json

{
  "firstName": "test2",
  "surname": "test4",
  "city": "default",
  "birthDate": "2012-01-02",
  "gender": "M",
  "interests": "test test"
}


###

GET http://localhost:8080/api/friend/1

###

GET http://localhost:8080/api/friend
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw


###

POST http://localhost:8080/api/friend
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw
Content-Type: application/json

{
  "friendId": 3
}

###

DELETE http://localhost:8080/api/friend/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjExMjk2MDk3fQ.q52vz1l-lCBA5_h9oCb0PdtK8fpuUm1GNNq9wt_fIZ06mgFQ2DbBExxCOmZilDqw51X0cv377mhYFh2WnRH0Nw


###

POST http://localhost:8080/actuator/refresh/

###
POST http://localhost:8080/refresh?name=db-mapping.profiles
###
POST http://localhost:8080/refresh?name=profilesDs