
spring:

  cache:
    jcache:
      config: classpath:ehcache.xml

  web:
    resources:
      cache:
        cachecontrol:
          cache-private: true
          max-age: 604800
  config:
    import: file:/datasources.yml


server:
  compression:
    enabled: true
  undertow:
    no-request-timeout: 10s
    options:
      server:
        IDLE_TIMEOUT: 10
jwt:
  secret: ${JWT_SECRET:test}
  expireMins: 9999999

logging:
  level:
    com.example: "debug"

management:
  endpoints:
    web:
      exposure:
        include: 'httptrace, *'

#bucket4j:
#  enabled: true
#  filters:
#    - url: \/api\/.*
#      rate-limits:
#        - bandwidths:
#            - capacity: 1000
#              time: 1
#              unit: hours