spring:

  cache:
    jcache:
      config: classpath:ehcache.xml

  web:
    resources:
      cache:
        cachecontrol:
          cache-private: true
          max-age: 604800
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
  redis:
    host: ${REDIS_HOST:localhost}
  data:
    cassandra:
      contact-points: ${CASSANDRA_ADDRESS:localhost:9042}



server:
  compression:
    enabled: true
  undertow:
    no-request-timeout: 10s
    options:
      server:
        IDLE_TIMEOUT: 10
jwt:
  secret: ${JWT_SECRET:test}
  expireMins: 9999999

logging:
  level:
    com.example: "debug"
    org.springframework.data.cassandra.core.cql: "debug"

management:
  endpoints:
    web:
      exposure:
        include: 'httptrace, *'

stomp:
  relay:
    host: ${STOMP_HOST:localhost}
    port: 61613


#bucket4j:
#  enabled: true
#  filters:
#    - url: \/api\/.*
#      rate-limits:
#        - bandwidths:
#            - capacity: 1000
#              time: 1
#              unit: hours